version: "3.8"
services:

  discovery:
    build: ./EurekaServer
    ports:
      - "8761:8761"
    image: "discovery-service"
    
  apigateway:
    container_name: apigateway
    build: ./apigetway
    ports:
      - "8089:8089"
    hostname: apigateway
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
    image: "apigateway"
    depends_on:
      - discovery
  
  
  reservation:
    container_name: reservation
    build: ./GestionReservation
    ports:
      - "8085:8085"
    hostname: reservation
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka

  offre:
      container_name: offre
      build: ./GestionOffre
      ports:
        - "8084:8084"
      hostname: offre
      environment:
        - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka